"""Generate the committed sample report from the real cached lecture transcript.

Runs the actual pipeline pieces (chunking, embedding, alignment, anomaly flag)
on a fixed set of realistic student notes on a real, messy ASR transcript, and
writes samples/sample_report.{json,md}. Uses the real NIM embedder when
NVIDIA_API_KEY is set; otherwise falls back to the deterministic FakeAIClient and
says so in the artifact header. Never fabricates real output.

The notes are chosen to show what embedding-based retrieval catches and what it
does not:
  - on-topic notes link to the lecture span they paraphrase;
  - an off-topic note matches nothing well and is flagged as an anomaly;
  - an on-topic-but-WRONG note ("love" vs the lecture's "hate") still links with
    high similarity — catching that needs the deferred LLM-as-judge layer, and
    the report says so.
"""

import json
import os

from koherent.ai.base import TranscriptWord
from koherent.config import settings
from koherent.pipeline.alignment import align
from koherent.pipeline.chunking import chunk_transcript
from koherent.pipeline.report import is_anomaly

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
FIXTURE = os.path.join(HERE, "..", "tests", "fixtures", "sample_transcript.json")
OUT_DIR = os.path.join(ROOT, "samples")

NOTES = [
    "small businesses lose roughly 3.5 to 4 percent of each sale to credit card fees",
    "credit card processing fees are often passed on to the consumer",
    "small businesses love using credit cards",  # on-topic but WRONG (lecture: "hate")
    "the mitochondria is the powerhouse of the cell",  # off-topic -> anomaly
]


def _load_words() -> list[TranscriptWord]:
    with open(FIXTURE) as fh:
        data = json.load(fh)
    return [TranscriptWord(**w) for w in data["words"]]


def _embedder():
    if settings.nvidia_api_key:
        from koherent.ai.embeddings import NIMEmbedder

        return NIMEmbedder(), "real:nvidia/nv-embedqa-e5-v5"
    from koherent.ai.fake import FakeAIClient

    return FakeAIClient(), "fake:deterministic-bag-of-words (no NVIDIA_API_KEY set)"


def main() -> None:
    words = _load_words()
    chunks = chunk_transcript(words)
    embedder, source = _embedder()

    chunk_vectors = embedder.embed([c.content for c in chunks])
    note_vectors = embedder.embed(NOTES)
    alignments = align(note_vectors, chunk_vectors)

    by_note = {a.note_index: a for a in alignments}
    items = []
    for i, note in enumerate(NOTES):
        a = by_note.get(i)
        chunk = chunks[a.chunk_index] if a is not None else None
        similarity = a.similarity if a is not None else None
        items.append(
            {
                "note": note,
                "matched_span_ms": [chunk.start_ms, chunk.end_ms] if chunk else None,
                "matched_lecture_text": chunk.content if chunk else None,
                "similarity": round(similarity, 4) if similarity is not None else None,
                "anomaly": is_anomaly(similarity, settings.anomaly_threshold),
            }
        )

    report = {
        "embedding_source": source,
        "anomaly_threshold": settings.anomaly_threshold,
        "items": items,
    }
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "sample_report.json"), "w") as fh:
        json.dump(report, fh, indent=2)

    lines = [
        "# Sample report",
        "",
        f"_Embedding source: `{source}`. Anomaly threshold: {settings.anomaly_threshold}._",
        "",
        "Generated by `backend/scripts/run_sample_report.py` from a real, messy ASR",
        "transcript (`backend/tests/fixtures/sample_transcript.json`).",
        "",
        "| Student note | Linked lecture span (ms) | Similarity | Anomaly |",
        "| --- | --- | ---: | :---: |",
    ]
    for it in items:
        span = ("%s–%s" % tuple(it["matched_span_ms"])) if it["matched_span_ms"] else "—"
        sim = it["similarity"] if it["similarity"] is not None else "—"
        flag = "⚠️ yes" if it["anomaly"] else "no"
        lines.append(f"| {it['note']} | {span} | {sim} | {flag} |")
    lines += [
        "",
        "Notes:",
        "- The off-topic note links to nothing relevant and is flagged.",
        "- The on-topic-but-wrong note (\"love\" vs the lecture's \"hate\") still links with",
        "  high similarity — embeddings match topic, not truth. Catching that is the job of",
        "  the deferred LLM-as-judge layer.",
    ]
    with open(os.path.join(OUT_DIR, "sample_report.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"wrote {OUT_DIR}/sample_report.json and .md (source: {source})")


if __name__ == "__main__":
    main()
